title: "Tiralabra - 2020 loppukesä"
entitle: "Data Structures Project, 2020 end of summer"
email: ''
description: "Helsingin yliopiston Aineopintojen harjoitustyö: Tietorakenteet ja algoritmit - kurssin kurssisivu"
endescription: "Course page for the Data Structures Project course at the University of Helsinki"
baseurl: '/loppukesa_2020' # the subpath of your site, e.g. /blog
url: https://tiralabra.github.io/loppukesa_2020/ # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

kramdown:
  parse_block_html: true

collections:
  fi:
    output: true
  en:
    output: true
